<?php

return [
    'uk' => [
        ['name' => 'Barclays', 'path' => '/images/partners/uk/barclays.svg'],
        ['name' => 'Lloyds Bank', 'path' => '/images/partners/uk/lloyds-bank.svg'],
        ['name' => 'Bank of Scotland', 'path' => '/images/partners/uk/bank-of-scotland.svg'],
        ['name' => 'Royal Bank of Scotland', 'path' => '/images/partners/uk/royal-bank-of-scotland.svg'],
        ['name' => 'HSBC', 'path' => '/images/partners/uk/hsbc.svg'],
        ['name' => 'Standard Chartered', 'path' => '/images/partners/uk/standard-chartered.svg'],
        ['name' => 'Monzo', 'path' => '/images/partners/uk/monzo.svg'],
        ['name' => 'Starling Bank', 'path' => '/images/partners/uk/starling-bank.svg'],
        ['name' => 'Revolut', 'path' => '/images/partners/uk/revolut.svg'],
        ['name' => 'Wise', 'path' => '/images/partners/uk/wise.svg'],
        ['name' => 'Arm', 'path' => '/images/partners/uk/arm.svg'],
        ['name' => 'Sage', 'path' => '/images/partners/uk/sage.svg'],
        ['name' => 'BT', 'path' => '/images/partners/uk/bt.svg'],
        ['name' => 'Vodafone', 'path' => '/images/partners/uk/vodafone.svg'],
        ['name' => 'O2', 'path' => '/images/partners/uk/o2.svg'],
        ['name' => 'Sky', 'path' => '/images/partners/uk/sky.svg'],
        ['name' => 'Virgin Media', 'path' => '/images/partners/uk/virgin-media.svg'],
        ['name' => 'Virgin Atlantic', 'path' => '/images/partners/uk/virgin-atlantic.svg'],
        ['name' => 'Deliveroo', 'path' => '/images/partners/uk/deliveroo.svg'],
        ['name' => 'Just Eat', 'path' => '/images/partners/uk/just-eat.svg'],
        ['name' => 'Tesco', 'path' => '/images/partners/uk/tesco.svg'],
        ['name' => 'Morrisons', 'path' => '/images/partners/uk/morrisons.svg'],
        ['name' => 'ASDA', 'path' => '/images/partners/uk/asda.svg'],
        ['name' => 'Boots', 'path' => '/images/partners/uk/boots.svg'],
        ['name' => 'Pearson', 'path' => '/images/partners/uk/pearson.svg'],
        ['name' => 'GSK', 'path' => '/images/partners/uk/gsk.svg'],
        ['name' => 'National Grid', 'path' => '/images/partners/uk/national-grid.svg'],
        ['name' => 'Rolls-Royce', 'path' => '/images/partners/uk/rolls-royce.svg'],
        ['name' => 'Aston Martin', 'path' => '/images/partners/uk/aston-martin.svg'],
        ['name' => 'Bentley', 'path' => '/images/partners/uk/bentley.svg'],
        ['name' => 'McLaren', 'path' => '/images/partners/uk/mclaren.svg'],
        ['name' => 'Channel 4', 'path' => '/images/partners/uk/channel-4.svg'],
        ['name' => 'DeepMind', 'path' => '/images/partners/uk/deepmind.svg'],
        ['name' => 'easyJet', 'path' => '/images/partners/uk/easyjet.svg'],
        ['name' => 'British Airways', 'path' => '/images/partners/uk/british-airways.svg'],
        ['name' => 'Unilever', 'path' => '/images/partners/uk/unilever.svg'],
        ['name' => 'Shell', 'path' => '/images/partners/uk/shell.svg'],
        ['name' => 'BP', 'path' => '/images/partners/uk/bp.svg'],
        ['name' => 'Marks & Spencer', 'path' => '/images/partners/uk/marks-and-spencer.svg'],
        ['name' => 'Skyscanner', 'path' => '/images/partners/uk/skyscanner.svg'],
    ],
];
